# Site settings
title: 人蛤乐园
SEOTitle: 韩建的博客 | HH Blog
header-img: img/post-bg-desk.jpg
email: herrizhan@gmail.com
description: "Every failure is leading towards success."
keyword: "Herriz, SAP, Finance, VBA, Scripting,Accounting"
#url: "http://qiubaiying.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/herrizd/herrizd.github.io.git" # you code repository

# Sidebar settings

sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     HERRIZ
#zhihu_username:     qiubaiying
#github_username:    qiubaiying
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: a5449f863efe9b95f849                            #生成的clientID
  clientSecret: 8e7c71e4c7f75cf47eb6fa9eb16f0ff8a8baf336    #生成的clientSecret
  repo: herrizd.github.io    #仓库名称
  owner: herrizd    #github用户名
  admin: herrizd
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-144543052-1'            # Format: UA-xxxxxx-xx
            # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 10              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    },{
#       title: "简书·BY",
#        href: "http://www.jianshu.com/u/e71990ada2fd"
#   },
     {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]

theme: jekyll-theme-cayman